// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var TodoApp$ReactHooksTemplate = require("./TodoApp.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(TodoApp$ReactHooksTemplate.make, {
          title: "what to do"
        }), "root");

/*  Not a pure module */
