// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var FrontSvg = require("../assets/riichi-mahjong-tiles/Regular/Front.svg");

var make = FrontSvg.default;

exports.make = make;
/* make Not a pure module */
